# Generated by Django 3.2.7 on 2022-01-22 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name_of_donation', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(null=True, upload_to='Donation/')),
            ],
            options={
                'verbose_name_plural': 'Add Donation',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.DeleteModel(
            name='Donations',
        ),
        migrations.AddField(
            model_name='adddonation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.category'),
        ),
    ]
