# Generated by Django 4.0 on 2022-01-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20220122_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatedMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('amount_paid', models.IntegerField(blank=True, default=0, null=True)),
                ('razorpay_id', models.CharField(blank=True, max_length=500, null=True)),
                ('transaction_date', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('flag', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
