# Generated by Django 4.0 on 2022-01-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_donatedmember_seva_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=60, null=True)),
                ('paid_amount', models.CharField(blank=True, max_length=60, null=True)),
                ('balance_amount', models.CharField(blank=True, max_length=60, null=True)),
                ('Date', models.DateField(blank=True, max_length=255, null=True)),
                ('Time', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
