# Generated by Django 3.2.7 on 2022-01-23 09:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', tinymce.models.HTMLField(default='<p>Add content</p>')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('active_main_image', models.ImageField(blank=True, null=True, upload_to='Activities/')),
                ('active_image1', models.ImageField(blank=True, null=True, upload_to='Activities/')),
                ('active_image2', models.ImageField(blank=True, null=True, upload_to='Activities/')),
                ('active_image3', models.ImageField(blank=True, null=True, upload_to='Activities/')),
                ('active_image4', models.ImageField(blank=True, null=True, upload_to='Activities/')),
                ('active_image5', models.ImageField(blank=True, null=True, upload_to='Activities/')),
                ('active_image6', models.ImageField(blank=True, null=True, upload_to='Activities/')),
                ('active_image7', models.ImageField(blank=True, null=True, upload_to='Activities/')),
                ('active_image8', models.ImageField(blank=True, null=True, upload_to='Activities/')),
                ('active_image9', models.ImageField(blank=True, null=True, upload_to='Activities/')),
                ('active_image10', models.ImageField(blank=True, null=True, upload_to='Activities/')),
                ('activity_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Add Activity',
            },
        ),
    ]
