# Generated by Django 4.0 on 2022-01-07 16:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Temple', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ImageField(null=True, upload_to='temple/')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='GuestHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ImageField(null=True, upload_to='temple/')),
            ],
            options={
                'verbose_name_plural': 'Guest House',
            },
        ),
        migrations.CreateModel(
            name='TempleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ImageField(null=True, upload_to='temple/')),
            ],
            options={
                'verbose_name_plural': 'Temple History',
            },
        ),
        migrations.DeleteModel(
            name='Temples',
        ),
    ]
