# Generated by Django 4.0 on 2022-01-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_gallery_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDarshan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gallery_image', models.ImageField(upload_to='gallery/')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
