# Generated by Django 3.2.7 on 2022-01-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0005_festivaldarshan_media_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='youtube_links',
            field=models.URLField(),
        ),
    ]
