# Generated by Django 4.0 on 2022-01-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Contact_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Contact_email', models.CharField(blank=True, max_length=500, null=True)),
                ('Contact_phone', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
