# Generated by Django 4.0 on 2022-01-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Contact_email',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Contact_phone',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Contact_name',
            new_name='phone',
        ),
    ]
