# Generated by Django 4.0 on 2022-01-07 16:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_contact_email_contact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=tinymce.models.HTMLField(default='null'),
            preserve_default=False,
        ),
    ]
