# Generated by Django 3.2.7 on 2022-01-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Queries',
            },
        ),
    ]
