# Generated by Django 4.0 on 2022-01-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, max_length=500, null=True)),
                ('client_image', models.ImageField(upload_to='clients/')),
                ('client_rating', models.IntegerField(blank=True, null=True)),
                ('client_comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clients Feedback',
            },
        ),
        migrations.CreateModel(
            name='Site_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('our_volunteers', models.IntegerField(null=True)),
                ('global_partners', models.IntegerField(null=True)),
                ('help_children', models.IntegerField(null=True)),
                ('medical_support', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Site Statistics',
            },
        ),
        migrations.DeleteModel(
            name='Festivals',
        ),
    ]
