# Generated by Django 3.2.7 on 2022-01-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_clients_feedback_site_stats_delete_festivals'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='name',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
