# Generated by Django 3.2.7 on 2022-01-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_slides_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients_Feedback',
        ),
    ]
