# Generated by Django 4.0 on 2022-01-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SrilaPrabhupada', '0002_alter_srilaprabhupada_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srilaprabhupada',
            name='title',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SrilaPrabhupada',
        ),
    ]
