# Generated by Django 4.0 on 2022-01-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SrilaPrabhupada', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhajans',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lectures',
            name='content',
        ),
        migrations.AddField(
            model_name='bhajans',
            name='file',
            field=models.FileField(default='null', upload_to='musics/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectures',
            name='file',
            field=models.FileField(default='null', upload_to='musics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bhajans',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bhajans/'),
        ),
        migrations.AlterField(
            model_name='lectures',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lectures/'),
        ),
    ]
