# Generated by Django 4.0 on 2022-01-07 15:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Seva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbhishekaSeva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', tinymce.models.HTMLField(default='<p>Add content</p>')),
                ('image', models.ImageField(null=True, upload_to='abhishekaseva/')),
            ],
            options={
                'verbose_name_plural': 'AbhishekaSeva',
            },
        ),
        migrations.CreateModel(
            name='AnnadanaSeva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', tinymce.models.HTMLField(default='<p>Add content</p>')),
                ('image', models.ImageField(null=True, upload_to='annadanaseva/')),
            ],
            options={
                'verbose_name_plural': 'AnnadanaSeva',
            },
        ),
        migrations.CreateModel(
            name='NaivedyaSeva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', tinymce.models.HTMLField(default='<p>Add content</p>')),
                ('image', models.ImageField(null=True, upload_to='naivedyaseva/')),
            ],
            options={
                'verbose_name_plural': 'NaivedyaSeva',
            },
        ),
        migrations.CreateModel(
            name='PushpalankaraSeva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', tinymce.models.HTMLField(default='<p>Add content</p>')),
                ('image', models.ImageField(null=True, upload_to='pushpalankaraseva/')),
            ],
            options={
                'verbose_name_plural': 'PushpalankaraSeva',
            },
        ),
        migrations.CreateModel(
            name='VastrabaranaSeva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', tinymce.models.HTMLField(default='<p>Add content</p>')),
                ('image', models.ImageField(null=True, upload_to='vastrabaranaseva/')),
            ],
            options={
                'verbose_name_plural': 'VastrabaranaSeva',
            },
        ),
        migrations.DeleteModel(
            name='Sevas',
        ),
    ]
