# Generated by Django 4.0 on 2022-01-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivals',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
